# Generated by Django 3.1.1 on 2020-09-29 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='account_activated',
            field=models.BooleanField(default=False),
        ),
    ]
