# Generated by Django 3.1.1 on 2020-09-29 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_account_activated'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='activation_id',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
