# Generated by Django 3.1.1 on 2020-09-30 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile_activation_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='activation_id',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
