# Generated by Django 3.1.1 on 2020-09-26 14:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.TextField()),
                ('date_device_added', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
