# Generated by Django 3.1.1 on 2020-10-18 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0002_file_file_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='in_bin',
            field=models.BooleanField(default=False),
        ),
    ]
